
// This is an autogenerated file from Firebase Studio.

import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';

const firebaseConfig = {
  "projectId": "stackswipe",
  "appId": "1:852716346687:web:88d2893886c144b930c78a",
  "storageBucket": "stackswipe.firebasestorage.app",
  "apiKey": "AIzaSyBVXvlNNOWxmSKGc-mboOoDAnPkVmjupZs",
  "authDomain": "stackswipe.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "852716346687"
};

const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
